name: 'Tests: node.js: shimmed Promise'

on: [pull_request, push]

jobs:
  majors:
    name: 'majors, promise-shimmed tests'
    continue-on-error: true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - '0.12'
          - '0.11'
          - '0.10'
          - '0.8'

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/run@main
        name: 'npm install && npm run test:promise-shimmed'
        with:
          node-version: ${{ matrix.node-version }}
          command: 'test:promise-shimmed'

  node:
    name: 'node, promise-shimmed tests'
    needs: [majors]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
